# Generated by Django 3.2.9 on 2021-12-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='料理名')),
                ('description', models.TextField(verbose_name='説明')),
                ('imageUrl', models.URLField(verbose_name='URL')),
                ('countryOfOrigin', models.CharField(max_length=120, verbose_name='国名')),
                ('typicalMealTime', models.IntegerField(choices=[(0, 'select meal time'), (1, 'morning'), (2, 'afternoon'), (3, 'evening')])),
                ('dateAdded', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.CreateModel(
            name='MealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='評価')),
                ('dateOfRating', models.DateTimeField(auto_now_add=True, verbose_name='評価日時')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealsite.meal', verbose_name='食事')),
            ],
            options={
                'verbose_name': 'MealRating',
                'verbose_name_plural': 'MealRatings',
            },
        ),
    ]
