# Generated by Django 3.2.9 on 2021-12-18 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Meal')),
                ('description', models.TextField(verbose_name='Description')),
                ('imageUrl', models.CharField(max_length=200, verbose_name='URL')),
                ('countryOfOrigin', models.CharField(max_length=120, verbose_name='Country')),
                ('dateAdded', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='MealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='Ratings')),
                ('dateOfRating', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealsite.meal', verbose_name='Meal')),
                ('voted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='投票者')),
            ],
            options={
                'verbose_name': 'MealRating',
                'verbose_name_plural': 'MealRatings',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(to='mealsite.Tag'),
        ),
    ]
