# Generated by Django 3.2.9 on 2021-12-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealsite', '0003_alter_meal_typicalmealtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='imageUrl',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
    ]
