# Generated by Django 3.2.9 on 2021-12-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealsite', '0004_alter_meal_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='countryOfOrigin',
            field=models.CharField(max_length=120, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='typicalMealTime',
            field=models.IntegerField(choices=[(1, 'morning'), (2, 'afternoon'), (3, 'evening')], verbose_name='Meal Time'),
        ),
    ]
